import { createClient } from 'npm:@supabase/supabase-js@2';
import { createRemoteJWKSet, jwtVerify } from 'npm:jose@6';

const firebaseProject = 'filo-app-1a2a5';
const firestore = `https://firestore.googleapis.com/v1/projects/${firebaseProject}/databases/(default)/documents`;
const keys = createRemoteJWKSet(new URL(
  'https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com'));
const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, apikey, content-type, x-client-info',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Cache-Control': 'no-store',
};
class Failure extends Error {
  constructor(public status: number) { super('Request failed'); }
}
function reply(data: unknown, status = 200) {
  return Response.json(data, { status, headers: cors });
}
async function document(path: string, token: string, optional = false) {
  const result = await fetch(`${firestore}/${path}`, {
    headers: { Authorization: `Bearer ${token}` }, signal: AbortSignal.timeout(15000),
  });
  if (optional && result.status === 404) return null;
  if (!result.ok) throw new Failure([401, 403, 404].includes(result.status) ? result.status : 503);
  return (await result.json()).fields ?? {};
}

Deno.serve(async (request: Request) => {
  if (request.method === 'OPTIONS') return new Response(null, { headers: cors });
  if (request.method !== 'POST') return reply({ error: 'method_not_allowed' }, 405);
  try {
    const token = request.headers.get('authorization')?.match(/^Bearer (\S+)$/i)?.[1];
    if (!token) throw new Failure(401);
    let uid: string;
    try {
      const { payload } = await jwtVerify(token, keys, {
        issuer: `https://securetoken.google.com/${firebaseProject}`,
        audience: firebaseProject, algorithms: ['RS256'], clockTolerance: 30,
        requiredClaims: ['sub', 'exp', 'iat', 'auth_time'],
      });
      const now = Math.floor(Date.now() / 1000) + 30;
      if (!payload.sub || payload.sub.length > 128 || typeof payload.iat !== 'number' ||
          payload.iat > now || typeof payload.auth_time !== 'number' || payload.auth_time > now) {
        throw new Failure(401);
      }
      uid = payload.sub;
    } catch { throw new Failure(401); }
    // Bound request parsing even when Content-Length is missing/chunked.
    const reader = request.body?.getReader();
    if (!reader) throw new Failure(400);
    let text = '', length = 0;
    const decoder = new TextDecoder();
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      length += value.byteLength;
      if (length > 4096) { await reader.cancel(); throw new Failure(413); }
      text += decoder.decode(value, { stream: true });
    }
    text += decoder.decode();
    let body;
    try { body = JSON.parse(text); } catch { throw new Failure(400); }
    const { action, classId, materialId } = body ?? {};
    // IDs generated by the app are alphanumeric Firestore auto IDs.
    if (typeof classId !== 'string' || typeof materialId !== 'string' ||
        !/^[A-Za-z0-9_-]{1,128}$/.test(classId) || !/^[A-Za-z0-9_-]{1,128}$/.test(materialId) ||
        !['upload', 'download', 'submission-upload', 'submission-download'].includes(action)) throw new Failure(400);

    const url = Deno.env.get('SUPABASE_URL');
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
    if (!url || !serviceKey) throw new Failure(503);
    // This key is supplied by Supabase at runtime. Never accept it from a client.
    const admin = createClient(url, serviceKey, {
      auth: { persistSession: false, autoRefreshToken: false },
    });
    const bucket = admin.storage.from('class-materials');
    if (action.startsWith('submission-')) {
      if (!/^[A-Za-z0-9_-]{1,128}$/.test(uid)) throw new Failure(400);
      const post = await document(`classes/${classId}/materials/${materialId}`, token);
      if (post.requiresSubmission?.booleanValue !== true) throw new Failure(403);
      const course = await document(`classes/${classId}`, token);
      const owner = course.instructorId?.stringValue === uid;
      if (action === 'submission-upload') {
        if (owner || course.archived?.booleanValue === true) throw new Failure(403);
        const due = post.dueAt?.timestampValue;
        if (due && (!Number.isFinite(Date.parse(due)) || Date.now() >= Date.parse(due))) throw new Failure(409);
        const profile = await document(`users/${encodeURIComponent(uid)}`, token);
        if (profile.role?.stringValue !== 'student') throw new Failure(403);
        await document(`classes/${classId}/enrollments/${encodeURIComponent(uid)}`, token);
        const existing = await document(`classes/${classId}/materials/${materialId}/submissions/${encodeURIComponent(uid)}`, token, true);
        if (existing) {
          const first = existing.firstSubmittedAt?.timestampValue ?? existing.submittedAt?.timestampValue;
          const minutes = Number(post.revisionMinutes?.integerValue ?? 5);
          if (existing.score || existing.status?.stringValue !== 'editing' || typeof first !== 'string' ||
              !Number.isFinite(Date.parse(first)) || Date.now() >= Date.parse(first) + minutes * 60000) throw new Failure(409);
        }
        const path = `class-submissions/${classId}/${materialId}/${uid}/${crypto.randomUUID()}`;
        const { data, error } = await bucket.createSignedUploadUrl(path, { upsert: false });
        if (error || !data) throw new Failure(503);
        return reply({ path, signedUrl: data.signedUrl });
      }
      const studentId = body.studentId;
      if (typeof studentId !== 'string' || !/^[A-Za-z0-9_-]{1,128}$/.test(studentId) ||
          (!owner && studentId !== uid)) throw new Failure(403);
      const submission = await document(`classes/${classId}/materials/${materialId}/submissions/${studentId}`, token);
      const index = body.attachmentIndex ?? 0;
      if (!Number.isInteger(index) || index < 0 || index >= 10) throw new Failure(400);
      const attachment = submission.attachments?.arrayValue?.values
        ? submission.attachments.arrayValue.values[index]?.mapValue?.fields
        : index === 0 ? submission : null;
      const path = attachment?.storagePath?.stringValue;
      if (typeof path !== 'string' || !new RegExp(`^class-submissions/${classId}/${materialId}/${studentId}/[a-f0-9-]{36}$`).test(path)) throw new Failure(404);
      const { data, error } = await bucket.createSignedUrl(path, 120);
      if (error || !data) throw new Failure(404);
      return reply({ signedUrl: data.signedUrl });
    }
    if (action === 'upload') {
      const course = await document(`classes/${classId}`, token);
      if (course.instructorId?.stringValue !== uid || course.archived?.booleanValue === true) {
        throw new Failure(403);
      }
      const posted = await document(`classes/${classId}/materials/${materialId}`, token, true);
      if (posted) throw new Failure(409);
      // Every grant gets an immutable destination. Retrying cannot replace bytes
      // beneath a published post. Failed publishes may leave orphan uploads.
      const path = `class-materials/${classId}/${materialId}/${crypto.randomUUID()}`;
      const { data, error } = await bucket.createSignedUploadUrl(path, { upsert: false });
      if (error || !data) throw new Failure(503);
      return reply({ path, signedUrl: data.signedUrl });
    }
    // Firebase evaluates the caller's actual Firestore membership rules here.
    // The client supplies IDs only; it cannot request an arbitrary storage path.
    const material = await document(`classes/${classId}/materials/${materialId}`, token);
    const path = material.storagePath?.stringValue;
    if (!['file', 'announcement'].includes(material.kind?.stringValue) || typeof path !== 'string' ||
        !new RegExp(`^class-materials/${classId}/${materialId}/[a-f0-9-]{36}$`).test(path)) {
      throw new Failure(404);
    }
    const { data, error } = await bucket.createSignedUrl(path, 120);
    if (error || !data) throw new Failure(404);
    return reply({ signedUrl: data.signedUrl });
  } catch (error) {
    const status = error instanceof Failure ? error.status : 503;
    // Never log caller tokens, signed URLs, or service keys.
    console.warn('material-files request failed', status);
    return reply({ error: 'material_access_failed' }, status);
  }
});
