// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlyebujHnr9-d0DGi--1WLc4YTiQOze1A',
    appId: '1:510027281592:web:9a2f2fc0e94f9dcd04704d',
    messagingSenderId: '510027281592',
    projectId: 'filo-app-1a2a5',
    authDomain: 'filo-app-1a2a5.firebaseapp.com',
    storageBucket: 'filo-app-1a2a5.firebasestorage.app',
    measurementId: 'G-Z7JZ27KHV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGbp_Im9rBgn0kSc-V_LZbbQmJZy03alk',
    appId: '1:510027281592:android:d5fe55ef9e03116a04704d',
    messagingSenderId: '510027281592',
    projectId: 'filo-app-1a2a5',
    storageBucket: 'filo-app-1a2a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvbhbXYZB37W2LPN7luGqvBshwaI7xsMM',
    appId: '1:510027281592:ios:7687b4fc418b8e3304704d',
    messagingSenderId: '510027281592',
    projectId: 'filo-app-1a2a5',
    storageBucket: 'filo-app-1a2a5.firebasestorage.app',
    iosClientId: '510027281592-6eh5182k10u94eurtnniqh3lg4addb5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.filo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvbhbXYZB37W2LPN7luGqvBshwaI7xsMM',
    appId: '1:510027281592:ios:7687b4fc418b8e3304704d',
    messagingSenderId: '510027281592',
    projectId: 'filo-app-1a2a5',
    storageBucket: 'filo-app-1a2a5.firebasestorage.app',
    iosClientId: '510027281592-6eh5182k10u94eurtnniqh3lg4addb5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.filo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlyebujHnr9-d0DGi--1WLc4YTiQOze1A',
    appId: '1:510027281592:web:648c6ccb50549a3504704d',
    messagingSenderId: '510027281592',
    projectId: 'filo-app-1a2a5',
    authDomain: 'filo-app-1a2a5.firebaseapp.com',
    storageBucket: 'filo-app-1a2a5.firebasestorage.app',
    measurementId: 'G-CJY0MDR0ZS',
  );
}
